FROM oven/bun:1@sha256:0733e50325078969732ebe3b15ce4c4be5082f18c4ac1a0f0ca4839c2e4e42a7 AS builder

WORKDIR /build

ARG VITE_REACT_APP_SERVER_URL
ENV VITE_REACT_APP_SERVER_URL=${VITE_REACT_APP_SERVER_URL}
ARG BACKEND_URL=https://api.apigiare.vn
ENV BACKEND_URL=${BACKEND_URL}

COPY web/default/package.json ./
COPY web/default/bun.lock ./
RUN bun install

COPY web/default ./
COPY VERSION ./

RUN VITE_REACT_APP_VERSION=$(cat VERSION) bun run build

FROM nginx:1.27-alpine

COPY deploy/nginx/frontend.conf.template /etc/nginx/templates/default.conf.template
COPY deploy/nginx/docker-entrypoint.d/40-frontend-env.sh /docker-entrypoint.d/40-frontend-env.sh
COPY --from=builder /build/dist /usr/share/nginx/html
RUN chmod +x /docker-entrypoint.d/40-frontend-env.sh

EXPOSE 80
